[Football Season Milestones]
percent = 65
sea_rush_yds = 1000
sea_pass_yds[] = 2000
sea_pass_yds[] = 3000
sea_rcv_yds = 1000
sea_tot_tack = 100
sea_sacks = 10
sea_tfl = 20
sea_fg_made = 20

;[Football Career Milestones]
;car_rush_yds = 
;car_rush_yds
;car_rcv_yds
;car_tot_tack
;car_tfl